# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.vm.box = "roboxes/ubuntu2204"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 1024
    vb.cpus = 2
  end

  # Configuração do nome da VM
  config.vm.define "Julio01-Julia02-Ryan03" do |aluno|
    aluno.vm.hostname = "Ubuntu-2204"
    # Rede privada
    aluno.vm.network "private_network", ip: "192.168.57.10"
    # Rede pública
    aluno.vm.network "public_network", bridge: "enp2s0"

    aluno.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
    end 
    
    aluno.vm.provider "virtualbox" do |vb|
      vb.name = "Julio01-Julia02-Ryan03"
    end
  end
end
